[features]
seeds = false
skip-lint = false
[programs.localnet]
offchain_delegate = "oCDofJsKeaWoyXWCtEY6vXgxvAdkmUdbXBRsedvUWkx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/vovacodes/.config/solana/id.json"

[scripts]
test = "npx mocha --node-option require=ts-node/register --extension ts -t 1000000 tests/**/*.ts"
